# Generated by Django 2.2 on 2020-03-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_received', models.CharField(blank=True, max_length=254, verbose_name='接收字节')),
                ('bytes_sent', models.CharField(blank=True, max_length=254, verbose_name='发送字节')),
                ('trusted_ip', models.CharField(blank=True, max_length=254, verbose_name='实际IP')),
                ('trusted_port', models.CharField(blank=True, max_length=254, verbose_name='实际端口')),
                ('remote_ip', models.CharField(blank=True, max_length=254, verbose_name='远端IP')),
                ('remote_netmask', models.CharField(blank=True, max_length=254, verbose_name='远端掩码')),
                ('common_name', models.CharField(blank=True, max_length=254, verbose_name='名称')),
                ('starting_time', models.CharField(blank=True, max_length=254, verbose_name='连接开始时间')),
                ('end_time', models.CharField(blank=True, max_length=254, verbose_name='连接结束时间')),
                ('protocol', models.CharField(blank=True, max_length=254, verbose_name='协议类型')),
            ],
            options={
                'verbose_name': '当前用户',
                'verbose_name_plural': '当前用户',
                'ordering': ('common_name',),
            },
        ),
        migrations.CreateModel(
            name='LogsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_received', models.CharField(blank=True, max_length=254, verbose_name='接收字节')),
                ('bytes_sent', models.CharField(blank=True, max_length=254, verbose_name='发送字节')),
                ('trusted_ip', models.CharField(blank=True, max_length=254, verbose_name='实际IP')),
                ('trusted_port', models.CharField(blank=True, max_length=254, verbose_name='实际端口')),
                ('remote_ip', models.CharField(blank=True, max_length=254, verbose_name='远端IP')),
                ('remote_netmask', models.CharField(blank=True, max_length=254, verbose_name='远端掩码')),
                ('common_name', models.CharField(blank=True, max_length=254, verbose_name='名称')),
                ('starting_time', models.CharField(blank=True, max_length=254, verbose_name='连接开始时间')),
                ('end_time', models.CharField(blank=True, max_length=254, verbose_name='连接结束时间')),
                ('protocol', models.CharField(blank=True, max_length=254, verbose_name='协议类型')),
            ],
            options={
                'verbose_name': '日志报告',
                'verbose_name_plural': '日志报告',
                'ordering': ('common_name',),
            },
        ),
    ]
