# Generated by Django 2.2 on 2020-03-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20200320_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentusers',
            name='online',
            field=models.CharField(blank=True, max_length=254, verbose_name='在线状态'),
        ),
    ]
