# Generated by Django 2.2 on 2020-03-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_currentusers_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentusers',
            name='local_port',
            field=models.CharField(blank=True, max_length=254, verbose_name='本地端口'),
        ),
    ]
