# Generated by Django 2.2 on 2020-03-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_currentusers_local_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentusers',
            old_name='remote_netmask',
            new_name='ifconfig_pool_netmask',
        ),
        migrations.RenameField(
            model_name='currentusers',
            old_name='remote_ip',
            new_name='ifconfig_pool_remote_ip',
        ),
    ]
